learn numpy

In [1]:
import numpy as np

creating array from list

In [2]:
arr_id = np.array([1,2,3,4,5])
print("1D array:" , arr_id)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("2Darray:" ,arr_2d)


1D array: [1 2 3 4 5]
2Darray: [[1 2 3]
 [4 5 6]]


List vs numpy array

In [3]:
py_list = [1,2,3]
print("python list multiplication", py_list * 2)

np_array = np.array([1,2,3])
print("python array multiplication", np_array * 2)

import time 
start = time.time()
py_list = [i*2 for i in range (1000000)]
print ("\n list operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n numpy operation time : ", time.time()- start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 list operation time :  0.18734145164489746

 numpy operation time :  0.00838017463684082


CREATING ARRAY FROM SCRATCH 

In [4]:
zero = np.zeros((3,4))
print("zero array: \n ", zero )

ones = np.ones((2,5))
print("ones array: \n ", ones )

full = np.full((9,4), 7)
print("full array: \n ", full )
# random array important 
random = np.random.random((4,5))
print("random array: \n ", random )
# sequence arrray important 
sequence = np.arange(0,10,2)
print("sequence array: \n ", sequence )

zero array: 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array: 
  [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array: 
  [[0.52827024 0.944201   0.42010103 0.86161466 0.39559125]
 [0.22599131 0.96048457 0.98131382 0.41763178 0.72175214]
 [0.55937602 0.4843353  0.36618963 0.10366187 0.95650491]
 [0.89621636 0.09612647 0.09517683 0.76820083 0.64655759]]
sequence array: 
  [0 2 4 6 8]


VECTOR, MATRIX, TENSOR


In [5]:
vector = np.array([1,2,3])
print("Vector: \n ", vector )

matrix = np.array,([[1,2,3],
                    [4,5,6]])
print("matrix: \n ", matrix )

tensor = np.array([[[1,2], [3,4]], 
                   [[5,6], [7,8]] ])
print("tensor: \n ", tensor )

Vector: 
  [1 2 3]
matrix: 
  (<built-in function array>, [[1, 2, 3], [4, 5, 6]])
tensor: 
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [6]:
arr = np.array([[1,2,3],[4,5,6]] )
print("shape: \n ", arr.shape )
print("dimension: \n ", arr.ndim)
print("size: \n ", arr.size)
print("Dtype: \n ", arr.dtype )

shape: 
  (2, 3)
dimension: 
  2
size: 
  6
Dtype: 
  int64


ARRAY RESHAPING 

In [ ]:
arr = np.arange(12)
print("orignal array", arr)

reshaped = arr.reshape((3,4))
print("\n reshape", reshaped)
# it returns copy
flattened = reshaped.flatten()
print("\n flattened array", flattened)

#  revel (return view , insted of copy)
raveled = reshaped.ravel()
print("\n reveled array", raveled)

# transpose
transpose = reshaped.T
print("\n transpose array", transpose)



orignal array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshape [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


: 