Numpy array operations 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing", arr[2:7])
print("with step", arr[1:8:3])
print("negative indexing", arr[-3])






basic slicing [3 4 5 6 7]
with step [2 5 8]
negative indexing 7


In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element ", arr_2d[1,2]) # 1 is row 2 element 2
print("entire row", arr_2d[1])
print("entire row", arr_2d[:, 1])

Specific Element  6
entire row [4 5 6]
entire row [2 5 8]


Sorting

In [4]:
unsorted = np.array([3,1,4,1,5,9,8])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2d array by column", np.sort(arr_2d_unsorted, axis =0)) # axis 0 lagane se 1,1 ek jagah
# 2,2 & 3,3 ek jagah, axis 1 rakhenege to 1,3 hoga 1,2 & 2,3 hoga

Sorted array [1 1 3 4 5 8 9]
Sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


Filter array

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0] #cyaha expressions likhte h [ isme]
print("even numbers", even_number)

even numbers [2 4 6 8]


Filter with mask 

In [6]:
mask = numbers > 5  # numbers arr hamne upar se liya , mask se sara data aayega evalution ke liye 
print("numbers greater than 5", numbers[mask])

numbers greater than 5 [6 7 8 9]


Fancy indexing vs np.where()

In [7]:
indices = [0,2,4] # 0,2,4 index waala no. print karega ye 
print(numbers[indices]) # numbers upar wala arr

where_result = np.where(numbers > 5) # where used to add condition 
print(where_result)
print("np where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
np where [6 7 8 9]


In [8]:
condition_arr = np.where(numbers > 5 ,"true", "false") # condition sahi h to wo return nahi hoga 
# uske bagal me true false h to wo return hoga 
print(condition_arr) # below for better understanding

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


In [9]:
# if(numbers > 5){
#     numbers * 4
# } else {
#     numbers
# }

Adding & removing data 

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combining_array = np.concatenate((arr1, arr2)) # here we combining 2 array
print(combining_array)

[1 2 3 4 5 6]


array compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,3])

print("Compatibility Shapes", a.shape == b.shape)

Compatibility Shapes True


In [12]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([[7,8,9]])

with_new_row = np.vstack((original, new_row)) #vstack add new rows
print(original)
print(with_new_row)

new_column = np.array([[1], [8]])
with_new_column = np.hstack((original,new_column )) # hstack adds new column
print("with new column", with_new_column)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
with new column [[1 2 3 1]
 [4 5 6 8]]


In [13]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2) # delete element of index 2 
print ("array after deletion " ,deleted)

array after deletion  [1 2 4 5]
